default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: '1qa'
  #host: localhost:3000

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: testdb

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
